# ##############################################################################
# vendor/openvela/boards/contest2026_224_board/CMakeLists.txt
#
# NUCLEO-N657X0-Q board adaptation for contest2026
#
# SPDX-License-Identifier: Apache-2.0
#
# ##############################################################################

add_subdirectory(src)
